import random
# a = random.randrange(1, 15, 5)
# print(a)
# b = random.randint(1, 15)
# print(b)
# c = random.getrandbits(4)
# print(c)
# l = list(range(100))
# l = [1.2 +2.j, 3.5, 8.6, 7.2, 1.5]
# # print(l)
# # random.shuffle(l)
# print(l)
# # l_r = random.choice(l)
# # print(l_r)
# sam = random.sample(l, 3)
# print(sam)
# print(random.random())
# print(random.uniform(0.0, 10.5))
# print(random.triangular(0.0, 10.5, 2.0))
import statistics as ss
# l = list(range(5, 76, 3))
# print(l)
# print(statistics.mean(l))
# print(statistics.fmean(l))
# print(statistics.geometric_mean(l))
# print(statistics.harmonic_mean(l))
l2 = [11.0, 15.2, 17.3, 19.8, 98.2]
# print(statistics.median(l2))
# print(statistics.median_low(l2))
# print(statistics.median_high(l2))
print(ss.mean(l2))